### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kennethlombardi**
## Problem
The sentence sounded odd with the extra word

## Solution
Remove the word

### CODE REVIEW

**Comment by kennethlombardi** [comment]
🔔 
@andrewpaliga 
@louiskearns

**Comment by louiskearns** [comment]
'in your integration' sounds best to me.

**Comment by andrewpaliga** [comment]
Agree, @kennethlombardi thanks for the change, can we add "your"?

**Comment by kennethlombardi** [comment]
🔔  @andrewpaliga @louiskearns

**Pull request merged**
